config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "static_pages/about"
  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :habits do
    post 'habit_schedules/:checkbox_id/done', to: 'habit_schedules#done', as: :done
    post 'habit_schedules/:checkbox_id/notdone', to: 'habit_schedules#notdone', as: :notdone
    put :sort
  end
  post "/guest", to: "guest_sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkbox.rb
class Checkbox < HabitSchedule
end

app/models/evaluation.rb
class Evaluation < HabitSchedule
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :habit_schedules, dependent: :destroy
  has_many :habit_active_days_of_the_weeks, dependent: :destroy

  include RankedModel
  ranks :row_order, with_same: :user_id

  validates :user_id,
            presence: true

  validates :name,
            presence: true,
            length: { maximum: 30, minimum: 1 }

  validates :icon,
            presence: true

  validates :datatype,
            presence: true

  validates :active_day,
            presence: true
end

app/models/habit_active_days_of_the_week.rb
class HabitActiveDaysOfTheWeek < ApplicationRecord
  belongs_to :habit
end

app/models/habit_schedule.rb
class HabitSchedule < ApplicationRecord
  belongs_to :user
  belongs_to :habit
end

app/models/number.rb
class Number < HabitSchedule
end

app/models/user.rb
class User < ApplicationRecord
  has_many :habits, dependent: :destroy
  has_many :habit_schedules, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :name,
            presence: true,
            length: { maximum: 16 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze # for email
  validates :email,
            presence: true,
            length: { maximum: 30 + 13 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 6 },
            allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to new_session_url
    end
  end
end

app/controllers/guest_sessions_controller.rb
class GuestSessionsController < ApplicationController
  def create
    user = User.find_by(email: "test@example.com")
    log_in(user)
    flash[:success] = "ゲストユーザーとしてログインしました"
    redirect_to root_path
  end
end

app/controllers/habit_schedules_controller.rb
class HabitSchedulesController < ApplicationController
  def done
    @checkbox = Checkbox.all.find(params[:checkbox_id])
    @checkbox.update(checkbox: true)
  end

  def notdone
    @checkbox = Checkbox.all.find(params[:checkbox_id])
    @checkbox.update(checkbox: false)
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :logged_in_user

  def index
    @habits = current_user.habits
  end

  def show
    @habit = current_user.habits.find(params[:id])
  end

  def new
    @habit = current_user.habits.new

    case @habit.datatype
    when "checkbox"
      @checkbox = Checkbox.new
    when "number"
      @number = Number.new
    when "evaluation"
      @evaluation = Evaluation.new
    end
  end

  def create
    @habit = current_user.habits.new(habit_params)

    if @habit.save
      case @habit.datatype
      when "checkbox"
        -14.upto(15) do |i|
          @checkbox = Checkbox.create(habit_id: @habit.id, scheduled_date: Date.today + i, user_id: current_user.id)
        end
      when "number"
        -14.upto(15) do |i|
          @number = Number.create(habit_id: @habit.id, scheduled_date: Date.today + i, user_id: current_user.id)
        end
      when "evaluation"
        -14.upto(15) do |i|
          @evaluation = Number.create(habit_id: @habit.id, scheduled_date: Date.today + i, user_id: current_user.id)
        end
      end

      flash[:success] = "習慣を作成しました"
      redirect_to habits_url
    else
      render "new"
    end
  end

  def edit
    @habit = current_user.habits.find(params[:id])
  end

  def update
    @habit = current_user.habits.find(params[:id])
    if @habit.update(habit_params)
      flash[:success] = "習慣を更新しました"
      redirect_to habits_url
    else
      render "edit"
    end
  end

  def destroy
    @habit = current_user.habits.find(params[:id])
    @habit.destroy
    flash[:success] = "習慣を削除しました"
    redirect_to habits_url
  end

  def sort
    habit = Habit.find(params[:habit_id])
    habit.update(habit_params)
    render body: nil
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :icon, :row_order_position, :datatype, active_day: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "ログインしました"
      redirect_to root_url
    else
      flash.now[:danger] = "入力された情報に間違いがあります"
      render "new"
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @habits = current_user.habits.rank(:row_order).order(:id)
      @habit_schedules = current_user.habit_schedules.order(:id)
      @checkboxes = Checkbox.all.where(user_id: current_user.id).order(:id)
      @numbers = Number.all.where(user_id: current_user.id)
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーを登録しました"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザーを更新しました"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "習慣管理アプリ"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/habit_schedules/_list_of_checkboxes.html.erb
<% @checkboxes.each do |checkbox| %>
  <% if checkbox.habit.active_day.include?(display_date.wday.to_s) %>
    <% if checkbox.scheduled_date == display_date %>
      <%= content_tag "tr", class: "item" do %>
        <% if checkbox.checkbox == true %>
          <%= content_tag "td", id: "checkbox-#{checkbox.id}", class: "done-css" do %>
            <i class="<%= checkbox.habit.icon %> fa-lg fa-fw"></i> <%= checkbox.habit.name %>
          <% end %>
        <% else %>
          <%= content_tag "td", id: "checkbox-#{checkbox.id}" do %>
            <i class="<%= checkbox.habit.icon %> fa-lg fa-fw"></i> <%= checkbox.habit.name %>
          <% end %>
        <% end %>
        <td class="text-right">
          <%= link_to habit_done_path(habit_id: checkbox.habit.id, checkbox_id: checkbox.id), method: :post, remote: true do %>
            <i class="fas fa-check fa-lg fa-fw"></i>
          <% end %>
          <%= link_to habit_notdone_path(habit_id: checkbox.habit.id, checkbox_id: checkbox.id), method: :post, remote: true do %>
            <i class="fas fa-times fa-lg fa-fw"></i>
          <% end %>
        </td>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/habit_schedules/done.js.erb
document.getElementById("checkbox-<%= @checkbox.id %>").style.color = "blue";

app/views/habit_schedules/notdone.js.erb
document.getElementById("checkbox-<%= @checkbox.id %>").style.color = "gray";

app/views/habits/edit.html.erb
<% provide(:title, "習慣タスク編集") %>
<h1 class="text-center"><i class="far fa-edit"></i> 習慣タスク編集</h1>
<%= form_with(model: @habit, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "習慣タスクの名前" %>
  </div>
  <div class="form-group d-flex justify-content-between validate-button">
    <%= f.radio_button :icon, "fas fa-check-circle", id: "001" %>
    <%= f.label :icon, for: "001" do %>
      <i class="fas fa-check-circle fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-pencil-alt", id: "002" %>
    <%= f.label :icon, for: "002" do %>
      <i class="fas fa-pencil-alt fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-laptop", id: "003" %>
    <%= f.label :icon, for: "003" do %>
      <i class="fas fa-laptop fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-book", id: "004" %>
    <%= f.label :icon, for: "004" do %>
      <i class="fas fa-book fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-running", id: "005" %>
    <%= f.label :icon, for: "005" do %>
      <i class="fas fa-running fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-dumbbell", id: "006" %>
    <%= f.label :icon, for: "006" do %>
      <i class="fas fa-dumbbell fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "far fa-check-square", id: "007" %>
    <%= f.label :icon, for: "007" do %>
      <i class="far fa-check-square fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-book-open", id: "008" %>
    <%= f.label :icon, for: "008" do %>
      <i class="fas fa-book-open fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-home", id: "009" %>
    <%= f.label :icon, for: "009" do %>
      <i class="fas fa-home fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "far fa-copy", id: "010" %>
    <%= f.label :icon, for: "010" do %>
      <i class="far fa-copy fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-camera", id: "011" %>
    <%= f.label :icon, for: "011" do %>
      <i class="fas fa-camera fa-lg"></i>
    <% end%>
  </div>
  <div class="form-group d-flex">
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 0, nil %><span style="font-size: 18px"> 日</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 1, nil %><span style="font-size: 18px"> 月</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 2, nil %><span style="font-size: 18px"> 火</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 3, nil %><span style="font-size: 18px"> 水</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 4, nil %><span style="font-size: 18px"> 木</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 5, nil %><span style="font-size: 18px"> 金</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 6, nil %><span style="font-size: 18px"> 土</span>
    </label>
  </div>
  <div class="form-group">
    <%= f.select :datatype, options_for_select({ "チェックボックス（日々のタスク管理に使ってください）" => "checkbox"}), {}, class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit "習慣タスクを編集する", class: "btn btn-outline-secondary form-control rounded-pill submitBtn" %>
  </div>
  <div class="text-center deleteLink">
    <%= link_to habit_path(@habit.id), class: "small", method: :delete, data: { confirm: "習慣タスクを本当に削除してよろしいですか？" } do %>
      <i class="fas fa-trash"></i> 習慣タスクを削除
    <% end %>
  </div>
<% end %>

app/views/habits/index.html.erb
<% provide(:title, "習慣の設定") %>
<div class="flexContainer">
  <h1><i class="fas fa-list-ul"></i> 習慣の設定</h1>
  <%= link_to new_habit_path, class: "btn btn-outline-secondary rounded-pill" do %>
    新しく習慣を作成する
  <% end %>
</div>
<div class="row">
  <% @habits.each do |habit| %>
    <div class="col-3">
      <div class="text-center linkAction">
        <%= link_to edit_habit_path(habit.id), class: "edit-habit-link" do %>
          <i class="<%= habit.icon %> fa-3x"></i><br>
          <%= habit.name.truncate(6) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/habits/new.html.erb
<% provide(:title, "習慣タスク作成") %>
<h1 class="text-center"><i class="far fa-calendar-check"></i> 習慣タスク作成</h1>
<%= form_with(model: @habit, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "習慣タスクの名前" %>
  </div>
  <div class="form-group d-flex justify-content-between validate-button">
    <%= f.radio_button :icon, "fas fa-check-circle", id: "001", checked: true %>
    <%= f.label :icon, for: "001" do %>
      <i class="fas fa-check-circle fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-pencil-alt", id: "002" %>
    <%= f.label :icon, for: "002" do %>
      <i class="fas fa-pencil-alt fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-laptop", id: "003" %>
    <%= f.label :icon, for: "003" do %>
      <i class="fas fa-laptop fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-book", id: "004" %>
    <%= f.label :icon, for: "004" do %>
      <i class="fas fa-book fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-running", id: "005" %>
    <%= f.label :icon, for: "005" do %>
      <i class="fas fa-running fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-dumbbell", id: "006" %>
    <%= f.label :icon, for: "006" do %>
      <i class="fas fa-dumbbell fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "far fa-check-square", id: "007" %>
    <%= f.label :icon, for: "007" do %>
      <i class="far fa-check-square fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-book-open", id: "008" %>
    <%= f.label :icon, for: "008" do %>
      <i class="fas fa-book-open fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-home", id: "009" %>
    <%= f.label :icon, for: "009" do %>
      <i class="fas fa-home fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "far fa-copy", id: "010" %>
    <%= f.label :icon, for: "010" do %>
      <i class="far fa-copy fa-lg"></i>
    <% end%>
    <%= f.radio_button :icon, "fas fa-camera", id: "011" %>
    <%= f.label :icon, for: "011" do %>
      <i class="fas fa-camera fa-lg"></i>
    <% end%>
  </div>
  <div class="form-group d-flex">
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 0, nil %><span style="font-size: 18px"> 日</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 1, nil %><span style="font-size: 18px"> 月</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 2, nil %><span style="font-size: 18px"> 火</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 3, nil %><span style="font-size: 18px"> 水</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 4, nil %><span style="font-size: 18px"> 木</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 5, nil %><span style="font-size: 18px"> 金</span>
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :active_day, {multiple: true}, 6, nil %><span style="font-size: 18px"> 土</span>
    </label>
  </div>
  <div class="form-group">
    <%= f.select :datatype, options_for_select({ "チェックボックス（日々のタスク管理に使ってください）" => "checkbox"}), {}, class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit "習慣タスクを作成する", class: "btn btn-outline-secondary form-control rounded-pill submitBtn" %>
  </div>
<% end %>

app/views/habits/show.html.erb
<% provide(:title, @habit.name) %>
<div class="card">
  <h5 class="card-header"><%= @habit.name %></h5>
  <div class="card-body">
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Copyright © 2018 AsaiShinji All Rights Reserved.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand p-4">
    <%= link_to "習慣管理アプリ", root_path, data: {"turbolinks" => false}, class: "navbar-brand logo-fontsize" %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <%= link_to "使い方", static_pages_about_path, class: "nav-link" %>
      </ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to habits_path, class: "nav-link habit-path-link" do %>
              <i class="fas fa-cog fa-lg"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to current_user, class: "nav-link user-path-link" do %>
              <i class="fas fa-user fa-lg"></i>
            <% end %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to new_session_path, class: "nav-link" do %>
            ログイン
          <% end %>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      エラーが<%= object.errors.count %>個あります
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<% date_range.each_slice(7) do |week| %>
  <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
    <% week.each do |day| %>
      <%= content_tag :td, class: calendar.td_classes_for(day) do %>
        <div class="only-flex">
          <%= link_to calendar.url_for_previous_view do %>
            <i class="fas fa-angle-left fa-3x"></i>
          <% end %>
          <div class="day-font-size">
            <%= day %> <small>(<%= t('date.abbr_day_names')[day.wday] %>)</small>
          </div>
          <%= link_to calendar.url_for_next_view do %>
            <i class="fas fa-angle-right fa-3x"></i>
          <% end %>
        </div>
        <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
          <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
        <% else %>
          <% passed_block.call day, sorted_events.fetch(day, []) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<h1 class="text-center"><i class="fas fa-user-edit"></i> プロフィール編集</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "名前" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード確認" %>
  </div>
  <div class="text-center">
    <%= f.submit "プロフィールを編集する", class: "btn btn-outline-secondary form-control rounded-pill submitBtn" %>
  </div>
  <div class="text-center deleteLink">
    <%= link_to user_path(current_user), class: "small", method: :delete, data: { confirm: "データは元に戻せません。本当に削除してよろしいですか？" } do %>
      <i class="fas fa-trash"></i> アカウントを削除
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<h1 class="text-center"><i class="fas fa-user-plus"></i> 新規登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object%>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "名前" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード確認" %>
  </div>
  <div class="text-center">
    <%= f.submit "新規登録する", class: "btn btn-outline-secondary form-control rounded-pill submitBtn" %>
  </div>
  <div class="text-center loginLink">
    <%= link_to new_session_path, class: "small" do %>
      <i class="fas fa-sign-in-alt"></i> ログイン
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% if current_user.email == "test@example.com"  %>
  <h1 class="text-center"><i class="fas fa-user fa-lg"></i> ゲストユーザー</h1>
  <div class="flexContainer justify-content-center">
    <%= link_to session_path(current_user), class: "btn btn-outline-secondary rounded-pill", method: :delete do %>
      <i class="fas fa-sign-out-alt"></i> ログアウト
    <% end %>
  </div>
<% else %>
  <h1 class="text-center"><i class="fas fa-user fa-lg"></i> <%= @user.name %></h1>
  <div class="flexContainer justify-content-center">
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary rounded-pill" do %>
      <i class="fas fa-user-edit"></i> プロフィール編集
    <% end %>
    &nbsp;&nbsp;
    <%= link_to session_path(current_user), class: "btn btn-outline-secondary rounded-pill", method: :delete do %>
      <i class="fas fa-sign-out-alt"></i> ログアウト
    <% end %>
  </div>
<% end %>